export default Images = {
  CardTopHolder: require('./idCard.png'),
  UniversityName: require('./uniName.png'),
  Logo: require('./Logo/Logo.png'),
  ConfirmBanner: require('./ConfirmBanner/ConfirmBanner.png'),
  BarCodeIcon: require('./barcode.png'),
  DiagnosisImage: require('./innerImage.png'),
  FooterIcon: require('./footerIcon.png'),
  HumanIcon: require('./humanIcon.png'),
  ImageBackgroundIcon: require('./GroupImg.png'),
  News1: require('./news1.png'),
  News2: require('./news2.png'),
  News3: require('./news3.png'),
  NewsLogo1: require('./logo1.png'),
  NewsLogo2: require('./logo2.png'),
  NewsDetail: require('./detailINewsImage.png'),
  bbcNewsIcon: require('./BBCnews.png'),
  Bg1: require('./BG1.png'),
  Bg2: require('./bg2.png'),
};
